title: Acemad's Vault
email: ouessai.aes@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: acemad.ga # the subpath of your site, e.g. /blog
url: "http://acemad.ga" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Acemad_
github_username:  Acemad

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

paginate: 5

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
